[package]
name = "x-super"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.13"
thiserror = "2.0.11"
two_percent = { version = "0.12.3", default-features = false }
which = "7.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
rust-ini = "0.21.1"
